### PR TITLE
added database setup and full CRUD for managing users

### PR DESCRIPTION
**Pull request by pepsipu**
added sql and CRUD for dealing with users to auth.js. ginkoid said no orms and pure sql, so that's done

using "pg" since aaron said you guys are gonna use postgres, and pooling is set up for it
appropriate env variables are stated at the top of server/database/auth.js

asynced everything since async > promises

yup

### CODE REVIEW

**Comment by ginkoid** [comment]
this has already been implemented by #2

**Comment by pepsipu** [comment]
unlucky, oh well

**Comment by chen-robert** [comment]
Sorry for the duplicate work @pepsipu, if you want to contribute I can split up the database tasks with you in the future so we don't accidentally do the same thing again.

**Comment by pepsipu** [comment]
don't worry @chen-robert, I should have asked if anyone was doing it first. Do you mind if I dm you on discord for other tasks that need to get done?

**Comment by chen-robert** [comment]
Yeah sure, that'd be great @pepsipu

**Pull request closed without merging**
